### ISSUE TITLE
Freeze creating a composition keyframe in  a Timeline. can't be created

### ISSUE THREAD

**Issue by HydeNaut** [KairosResearchLab/Kairos#282]
![image](https://github.com/KairosResearchLab/Kairos/assets/67781825/0b3c889f-e3e8-47be-83a4-6130cc1c1f6e)

File to reproduce [CreateCompositionKeyframe.zip](https://github.com/KairosResearchLab/Kairos/files/11907817/CreateCompositionKeyframe.zip)
 Error message:

> Error: Value cannot be null. (Parameter 'source')
>    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
>    at _VL_Kairos_TimelineUI_.Kairos.TimelineUI.ImGui.NewCompositionKeyframeMenu_C.Update(IComposition_I Composition_In, TimelineUI_C Timeline_UI_In, Context Context_In, Context& Context_Out)
>    at _VL_Kairos_TimelineUI_.Kairos.TimelineUI.ImGui.CreateEntry_RptXgWIwZAqO1Eur4W3eym.<>c__DisplayClass2_0.<Update>b__4(Object stateInput_87, IReadOnlyList`1 inputs_88, IReadOnlyList`1 incomingLinks_89, Object& stateOutput_92, Spread`1& outputs_93)
>    at VL.AppServices.CompilerServices.CustomRegion.CustomRegionPatch.Update(IReadOnlyList`1 inputs, Spread`1& outputs, IReadOnlyList`1 incomingLinks)
>    at _VL_ImGui_.ReGui.ImmediateModeNode_C.<>c__DisplayClass2_0.<Update>b__0(Context Obj_In_50)
>    at VL.ImGui.Widget.Update(Context context)
>    at VL.ImGui.Widgets.Modal.UpdateCore(Context context)
>    at VL.ImGui.Widget.Update(Context context)
>    at VL.ImGui.Widgets.RetainedMode.UpdateCore(Context context)
>    at VL.ImGui.Widget.Update(Context context)
>    at _VL_ImGui_.ImGui.Widgets.Popup_Modal_JGtjBEEApdlMejuKHZrrax.Update(ICustomRegion Region_In, Context Context_In, String Label_In, IChannel`1 Visible_In, IChannel`1 Closing_In, IChannel`1 Bounds_In, IStyle Style_In, ImGuiWindowFlags Flags_In, ProcessLifespan Lifespan_In, Context& Context_Out, Boolean& Close_Clicked_Out, Boolean& Content_Is_Visible_Out)
>    at _VL_Kairos_TimelineUI_.Kairos.TimelineUI.ImGui.CreateEntry_RptXgWIwZAqO1Eur4W3eym.Update(TimelineUI_C Timeline_UI_In, Context Context_In, Func`2 Track_Create_Func_In, IStyle Style_In, Context& Context_Out)
>    at _VL_Kairos_TimelineUI_.Kairos.TimelineUI.ImGui.TimelineMainMenu_C.Update_(Context Context_In, Context& Context_Out)
>    at _VL_Kairos_TimelineUI_.Kairos.TimelineUI.ImGui.TimelineMainMenu_C._VL_Kairos_Common_.Kairos.Common.IMainMenu_I.Update(Context Context_In, Context& Context_Out)
>    at _VL_Kairos_.Kairos.KairosEditor_C.<>c__DisplayClass2_0.<Update_>b__2(Object stateInput_161, IReadOnlyList`1 inputs_162, IReadOnlyList`1 incomingLinks_163, Object& stateOutput_165, Spread`1& outputs_166)
>    at VL.AppServices.CompilerServices.CustomRegion.CustomRegionPatch.Update(IReadOnlyList`1 inputs, Spread`1& outputs, IReadOnlyList`1 incomingLinks)
>    at _VL_ImGui_.ReGui.ImmediateModeNode_C.<>c__DisplayClass2_0.<Update>b__0(Context Obj_In_50)
>    at VL.ImGui.Widget.Update(Context context)
>    at VL.ImGui.Widgets.MainMenuBar.UpdateCore(Context context)
>    at VL.ImGui.Widget.Update(Context context)
>    at VL.ImGui.Widgets.RetainedMode.UpdateCore(Context context)
>    at VL.ImGui.Widget.Update(Context context)
>    at _VL_ImGui_.ImGui.Widgets.MainMenuBar_Cw2FZxDBFWTL9aiaIWX5BJ.Update(Context Context_In, IStyle Style_In, ICustomRegion Region_In, Context& Context_Out)
>    at _VL_Kairos_.Kairos.KairosEditor_C.<>c__DisplayClass2_0.<Update_>b__0(Object stateInput_117, IReadOnlyList`1 inputs_118, IReadOnlyList`1 incomingLinks_119, Object& stateOutput_127, Spread`1& outputs_128)
>    at VL.AppServices.CompilerServices.CustomRegion.CustomRegionPatch.Update(IReadOnlyList`1 inputs, Spread`1& outputs, IReadOnlyList`1 incomingLinks)
>    at _VL_ImGui_.ReGui.ImmediateModeNode_C.<>c__DisplayClass2_0.<Update>b__0(Context Obj_In_50)
>    at VL.ImGui.Widget.Update(Context context)
>    at VL.ImGui.ToSkiaLayer.Update(Widget widget, Boolean dockingEnabled, Spread`1 fonts, IStyle Style)
>    at _VL_ImGui_Skia_.Graphics.Skia.Layer.ImGui_Pb0jmhYedzLP452JM5MUGn.Update(ICustomRegion Region_In, Boolean Docking_Enabled_In, Spread`1 Fonts_In, Boolean Add_Fullscreen_Window_In, IStyle Style_In, Boolean Use_Skia_Space_In, ILayer& Output_Out)
>    at _VL_Kairos_.Kairos.KairosEditor_C.Update_(ILayer& Output_Out)
>    at _callmenamesM2023M06M29_02_.__auto.callmenamesM2023M06M29_02Application_IipphmQjFFRPcz9jL09I4GProgram_.Update__TRACE__(callmenamesM2023M06M29_02Application_IipphmQjFFRPcz9jL09I4G __self, PatchTracer __tracer) in C:\Users\Igor\Documents\vvvv\gamma\Sketches\callmenames-2023-06-29_02.vl.cs:line 94
>    at _callmenamesM2023M06M29_02_.__auto.callmenamesM2023M06M29_02Application_IipphmQjFFRPcz9jL09I4GProgram_.Update(callmenamesM2023M06M29_02Application_IipphmQjFFRPcz9jL09I4G __self) in C:\Users\Igor\Documents\vvvv\gamma\Sketches\callmenames-2023-06-29_02.vl.cs:line 29

**Comment by natan-sinigaglia** [comment]
hey @HydeNaut  
I just tried to reproduce and it works here with the latest kairos version 1.1.7.
when you have time, can you double check again? cheers

**Comment by HydeNaut** [comment]
Yep I'll take a look a bit laterSent from Android deviceOn 4 Jul 2023 15:45, Natan Sinigaglia ***@***.***> wrote:
hey @HydeNaut
I just tried to reproduce and it works here with the latest kairos version 1.1.7.
when you have time, can you double check again? cheers
